version: '3'

services:
  php-main:
    container_name: tbd-main
    build: ./main
    environment:
      X_LISTEN: 0.0.0.0:8181
      FEATURE_FLAG_SHOW_PRODUCT_DETAILS_ON_LIST: 1
    working_dir: /app/public
    ports:
      - 8181:8181
    restart: always